# Generated by Django 5.1 on 2024-09-02 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_archiveduser_serviceplan_useractivitylog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='api_key_expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 9, 2, 18, 7, 5, 879840, tzinfo=datetime.timezone.utc)),
        ),
    ]
