# Generated by Django 5.1 on 2024-08-30 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='api.images'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='custom_images',
            field=models.ManyToManyField(blank=True, related_name='custom_pizzas', to='api.images'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='default_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_pizzas', to='api.images'),
        ),
    ]
