# Generated by Django 5.1 on 2024-08-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_images_ingredient_images_pizza_custom_images_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
