# Generated by Django 5.1 on 2024-08-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_images_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('vegetable', 'Vegetable'), ('meat', 'Meat'), ('dairy', 'Dairy'), ('other', 'Other')], default='other', max_length=100),
        ),
        migrations.AddField(
            model_name='pizza',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='api.category'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['name'], name='api_pizza_name_d9a614_idx'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['price'], name='api_pizza_price_5d4a31_idx'),
        ),
    ]
