# Generated by Django 5.1 on 2024-08-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pizza_default_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='default_image',
        ),
    ]
