# Generated by Django 5.1 on 2024-08-31 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_pizza_default_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient'},
        ),
        migrations.AlterModelOptions(
            name='pizza',
            options={'verbose_name': 'Pizza', 'verbose_name_plural': 'Pizzas'},
        ),
    ]
