# Generated by Django 5.1 on 2024-08-31 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_options_alter_image_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='some default description')),
            ],
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ingredient', 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='pizza',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pizza',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='allergens',
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['vegetarian'], name='api_pizza_vegetar_a776dc_idx'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['available'], name='api_pizza_availab_59a7c4_idx'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='ingredients', to='api.allergen'),
        ),
    ]
