# Generated by Django 5.1 on 2024-09-01 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_pizzahistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='api.category'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='image',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='api_categor_name_53a3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_deleted'], name='api_categor_is_dele_28b686_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_active'], name='api_categor_is_acti_5fb091_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['description'], name='api_image_descrip_90ca66_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_default'], name='api_image_is_defa_0d6b6a_idx'),
        ),
    ]
